accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from . import views


app_name = 'accounts'
urlpatterns = [
    url(r'^$', login_required(views.IndexView.as_view()), name='index'),
    url(r'^new$', views.NewView.as_view(), name='new'),
    url(r'^(?P<pk>[0-9]+)$', login_required(views.DetailView.as_view()), name='detail'),
    url(r'^(?P<pk>[0-9]+)/edit$', login_required(views.EditView.as_view()), name='edit'),
    url(r'^password/edit$', views.CustomPasswordChangeView.as_view(), name='edit_password'),     # login_required is no need
    url(r'^(?P<pk>[0-9]+)/delete$', login_required(views.DeleteView.as_view()), name='delete'),
    url(r'^login$', auth_views.login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout$', auth_views.logout, name='logout'),
]

django2_orig/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^todo/', include('todo.urls', namespace='todo')),
    url(r'^accounts/', include('accounts.urls')),
]

todo/urls.py
from django.conf.urls import url
from todo import views

urlpatterns = [
    # todo
    url(r'^todo/$', views.todo_list, name='todo_list'),   #
    url(r'^todo/list_no/$', views.todo_list_no, name='todo_list_no'),   #
    url(r'^todo/add/$', views.todo_edit, name='todo_add'),  #
    url(r'^todo/mod/(?P<todo_id>\d+)/$', views.todo_edit, name='todo_mod'),  #
    url(r'^todo/del/(?P<todo_id>\d+)/$', views.todo_del, name='todo_del'),   #
]

accounts/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

todo/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Todo(models.Model):
    """todo"""
    name = models.CharField('name', max_length=255)
    detail = models.CharField('detail', max_length=255, blank=True)
    created_at = models.DateTimeField(auto_now_add = True, verbose_name= 'DATE',)
    memo = models.TextField(null=True)
    DONE = (
        ('Y', 'Yes'),
        ('N', 'No'),
    )
    dones = models.CharField(max_length=1, choices=DONE)
    
    def __str__(self):
        return self.name

accounts/forms.py
import copy

from django import forms
from django.contrib.auth.forms import PasswordChangeForm, UserChangeForm, UserCreationForm
from django.utils.translation import ugettext_lazy as _

from django.contrib.auth.models import User


username = forms.RegexField(
    max_length = 8,
    min_length = 3,
    regex = r'^[a-z][a-zA-Z0-9]+$',
    error_messages = {
        'invalid': _('please enter your password head as charactor, and please 8-16 charactor.'),
    },
    widget = forms.TextInput(attrs={'placeholder': 'Username'}),
)

password = forms.RegexField(
    max_length = 16,
    min_length = 8,
    regex = r'^[a-zA-Z][a-zA-Z0-9]+$',
    error_messages = {
        'invalid': _('please enter your password head as charactor, and please 3-8 charactor.'),
    },
    widget = forms.PasswordInput,
)

email = forms.EmailField(
    required = True,
    widget = forms.TextInput(attrs={'placeholder': 'Email'}),
)

password1 = copy.deepcopy(password)
password1.widget.attrs['placeholder'] = 'Password'
password2 = copy.deepcopy(password)
password2.widget.attrs['placeholder'] = 'Password (again)'
new_password1 = copy.deepcopy(password)
new_password1.widget.attrs['placeholder'] = 'New Password'
new_password2 = copy.deepcopy(password)
new_password2.widget.attrs['placeholder'] = 'New Password (again)'
old_password = copy.deepcopy(password)
old_password.widget.attrs['placeholder'] = 'Old Password'

def email_duplicate_check(email):
    try:
        User._default_manager.get(email=email)
    except User.DoesNotExist:
        return email
    raise forms.ValidationError(
        'Your address is already existing.'
    )


class CustomUserCreationForm(UserCreationForm):
    username = username
    password1 = password1
    password2 = password2
    email = email

    class Meta:
        model = User
        fields = (
            'username',
            'email',
        )

    def clean_email(self):
        email = self.cleaned_data['email']
        return email_duplicate_check(email)


class CustomUserChangeForm(UserChangeForm):
    username = username
    email = email

    class Meta:
        model = User
        fields = (
            'username',
            'password',
            'email',
        )

    def clean_email(self):
        user = self.instance      
        email = self.cleaned_data['email']
        if user.email == email:
            return email
        return email_duplicate_check(email)


class CustomPasswordChangeForm(PasswordChangeForm):
    new_password1 = new_password1
    new_password2 = new_password2
    old_password = old_password

todo/forms.py
from django.forms import ModelForm
from todo.models import Todo

class TodoForm(ModelForm):
    """TODO_Form"""
    class Meta:
        model = Todo
        fields = ('name', 'detail', 'memo', 'dones')

accounts/views.py
from django.contrib.auth.models import User
from django.contrib.auth.views import PasswordChangeView
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .forms import CustomPasswordChangeForm, CustomUserChangeForm, CustomUserCreationForm


# 
def get_queryset_for_detail_edit_delete(self):
    if self.request.user.is_superuser:
        return User.objects.filter(pk=self.kwargs['pk'])
    else:
        return User.objects.filter(pk=self.request.user.id)


class IndexView(ListView):
    template_name = 'accounts/index.html'

    def get_queryset(self):
        if self.request.user.is_superuser:
            return User.objects.all().order_by('id')
        else:
            return User.objects.filter(pk=self.request.user.id)


class NewView(CreateView):
    model = User
    form_class = CustomUserCreationForm
    template_name = 'accounts/new.html'
    success_url = './login'


class DetailView(DetailView):
    template_name = 'accounts/detail.html'

    def get_queryset(self):
        return get_queryset_for_detail_edit_delete(self)


class EditView(UpdateView):
    form_class = CustomUserChangeForm
    template_name = 'accounts/edit.html'

    def get_queryset(self):
        return get_queryset_for_detail_edit_delete(self)

    def get_success_url(self):
        return '../' + self.kwargs['pk']


class CustomPasswordChangeView(PasswordChangeView):
    form_class = CustomPasswordChangeForm
    template_name = 'accounts/edit_password.html'

    def get_success_url(self):
        return '../' + str(self.request.user.id)


class DeleteView(DeleteView):
    template_name = 'accounts/user_confirm_delete.html'
    success_url = '../'

    def get_queryset(self):
        return get_queryset_for_detail_edit_delete(self)

todo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse

from todo.models import Todo
from todo.forms import TodoForm

# Create your views here.
def todo_list(request):
    """todo_list"""
    todos = Todo.objects.all().order_by('id')
    return render(request,
                  'todo/todo_list.html',     # 
                  {'todos': todos})         # 

def todo_edit(request, todo_id=None):
    """todo_edit"""
    if todo_id:   
        todo = get_object_or_404(Todo, pk=todo_id)
    else:        
        todo = Todo()

    if request.method == 'POST':
        form = TodoForm(request.POST, instance=todo)  
        if form.is_valid():    
            todo = form.save(commit=False)
            todo.save()
            return redirect('todo:todo_list')
    else:    # GET
        form = TodoForm(instance=todo)  

    return render(request, 'todo/todo_edit.html', dict(form=form, todo_id=todo_id))
    
def todo_del(request, todo_id):
    """todo_del"""
    todo = get_object_or_404(Todo, pk=todo_id)
    todo.delete()
    return redirect('todo:todo_list')

def todo_list_no(request):
    """todo_list_no"""
    todos = Todo.objects.all().order_by('id')
    return render(request,
                  'todo/todo_list_no.html',     # 
                  {'todos': todos})         # 

accounts/templates/accounts/detail.html
{{ user.id }}<br>
{{ user.username }}<br>
{{ user.email }}<br>
{{ user.date_joined }}<br>
{{ user.last_login }}

accounts/templates/accounts/edit.html
<form method="post" action="./edit">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {{ form.errors.username }}
    {{ form.username }}
    {{ form.errors.email }}
    {{ form.email }}
    <input type="submit" value="Update">
</form>

accounts/templates/accounts/edit_password.html
<form method="post" action="{% url 'accounts:edit_password' %}">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {{ form.errors.new_password1 }}
    {{ form.new_password1 }}
    {{ form.errors.new_password2 }}
    {{ form.new_password2 }}
    {{ form.errors.old_password }}
    {{ form.old_password }}
    <input type="submit" value="Update Password">
</form>

accounts/templates/accounts/index.html
{% if user_list %}
    <table>
        <thead>
            <tr>
                <th>id</th><th>username</th><th>is_superuser</th><th>last_login</th>
            </tr>
        </thead>
        <tbody>
            {% for user in user_list %}
                <tr>
                    <td>{{ user.id }}</td><td>{{ user.username }}</td><td>{{ user.is_superuser }}</td><td>{{ user.last_login }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endif %}

accounts/templates/accounts/login.html
<form method="post" action="{% url 'accounts:login' %}">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {{ form.errors.username }}
    {{ form.username }}
    {{ form.errors.password }}
    {{ form.password }}
    <input type="submit" value="Login">
</form>

accounts/templates/accounts/new.html
<form method="post" action="{% url 'accounts:create' %}">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {{ form.errors.username }}
    {{ form.username }}
    {{ form.errors.password1 }}
    {{ form.password1 }}
    {{ form.errors.password2 }}
    {{ form.password2 }}
    {{ form.errors.email }}
    {{ form.email }}
    <input type="submit" value="Create">
</form>

accounts/templates/accounts/user_confirm_delete.html
<form method="post" action="./delete">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

todo/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta charset="UTF-8">
<title>{% block title %}My todos{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block extrahead %}{% endblock %}
</head>
<body>
  <div class="container">
    {% block content %}
      {{ content }}
    {% endblock %}
  </div>
</body>
</html>

todo/templates/todo/todo_edit.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}TODOの編集{% endblock title %}

{% block content %}
    <h3 class="page-header">TODOの編集</h3>
    {% if todo_id %}
    <form action="{% url 'todo:todo_mod' todo_id=todo_id %}" method="post" class="form-horizontal" role="form">
    {% else %}
    <form action="{% url 'todo:todo_add' %}" method="post" class="form-horizontal" role="form">
    {% endif %}
      {% csrf_token %}
      {{ form|bootstrap_horizontal }}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'todo:todo_list' %}" class="btn btn-default btn-sm">戻る</a>
{% endblock content %}

todo/templates/todo/todo_list.html
{% extends "base.html" %}

{% block title %}TODOの一覧{% endblock title %}

{% block extrahead %}
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
    <h3 class="page-header">TODOの一覧</h3>
    <a href="{% url 'todo:todo_add' %}" class="btn btn-default btn-sm">追加</a>
    <a href="{% url 'todo:todo_list_no' %}" class="btn btn-default btn-sm">未完了</a>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>名前</th>
          <th>詳細</th>
          <th>メモ</th>
          <th>作成日</th>
          <th>完了</th>
        </tr>
      </thead>
      <tbody>
        {% for todo in todos %}
        <tr>
          <td>{{ todo.name }}</td>
          <td>{{ todo.detail }}</td>
          <td>{{ todo.memo }}</td>
          <td>{{ todo.created_at }}</td>
          <td>{{ todo.dones }}</td>
          <td>
            <a href="{% url 'todo:todo_mod' todo_id=todo.id %}" class="btn btn-default btn-sm">修正</a>
            <a href="{% url 'todo:todo_del' todo_id=todo.id %}" class="btn btn-default btn-sm">削除</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
{% endblock content %}

todo/templates/todo/todo_list_no.html
{% extends "base.html" %}

{% block title %}TODOの一覧{% endblock title %}

{% block extrahead %}
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
    <h3 class="page-header">TODOの一覧</h3>
    <a href="{% url 'todo:todo_add' %}" class="btn btn-default btn-sm">追加</a>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>名前</th>
          <th>詳細</th>
          <th>メモ</th>
          <th>作成日</th>
          <th>完了</th>
        </tr>
      </thead>
      <tbody>
        {% for todo in todos %}
        {% if todo.dones == "N" %}
        <tr>
          <td>{{ todo.name }}</td>
          <td>{{ todo.detail }}</td>
          <td>{{ todo.memo }}</td>
          <td>{{ todo.created_at }}</td>
          <td>{{ todo.dones }}</td>
          <td>
            <a href="{% url 'todo:todo_mod' todo_id=todo.id %}" class="btn btn-default btn-sm">修正</a>
            <a href="{% url 'todo:todo_del' todo_id=todo.id %}" class="btn btn-default btn-sm">削除</a>
          </td>
        </tr>
        {% endif %}
        {% endfor %}
      </tbody>
    </table>
{% endblock content %}